package gay.bacoin.api.vih;

import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Random;

public class VIHFacts {

    private static VIHFacts instance;


    private ArrayList<Fact> facts = new ArrayList<>();
    public VIHFacts(){
        instance = this;
        loadFacts();
    }

    private void addFact(String desc, boolean value, String explanation){
        facts.add(new Fact(desc,value,explanation));
    }

    public void loadFacts(){
        //False facts
        addFact("Le SIDA on en guerit", false, "Même si des trithérapies performantes existent depuis 1996, on ne guérit toujours pas du SIDA. Les trithérapies permettent de \"mieux vivre\" avec le virus mais celui-ci reste toujours présent dans l'organisme. Une infection par le VIH s'évite en utilisant un moyen de prévention adapté à ses pratiques.");
        addFact("Le SIDA on en meure plus", false, "Dans le monde, 770 000 personnes sont décédées de maladies liées au sida en 2018, selon un rapport de l’ONUSIDA. En France, Les trithérapies ont fortement réduit le taux de mortalité. Cependant on compte chaque année plusieurs centaines de décès liés directement ou indirectement au VIH.");
        addFact("Le SIDA a ete cree en laboratoire par les americains", false, "La souche VIH-1 (la plus répandue dans le monde) a été sourcée chez les grands singes du sud du Cameroun. Le virus aurait franchi la barrière des espèces lors de chasses, par des morsures d'un singe infecté, par des écorchures lors du dépeçage de ces animaux, ou lors de la consommation de viande de brousse.");
        addFact("Le premier rapport sexuelprotege du SIDA", false, "C’est une contre-vérité absolue ! Avec un ou une partenaire inconnu-e, même s’il s’agit de votre premier rapport sexuel, il est important de se protéger en utilisant par exemple un préservatif masculin ou féminin.");
        addFact("La pilule protege du SIDA", false, "La pilule est un moyen contraceptif. Elle permet d’éviter une grossesse mais ne peut rien contre la transmission du VIH dans l'organisme lors d’un rapport sexuel non protégé. Un préservatif masculin ou féminin - s’il ne craque pas, s’il ne glisse pas - évite d'être contaminé par le VIH.");
        addFact("Le SIDA se transmet pas les moustiques ou les WC publique", false, "Les moustiques peuvent transmettre des virus tels que le chikungunya ou la dengue, mais pas le VIH. Dans des WC publics plus ou moins propres, vous risquez d’être incommodé-e-s par de vilaines petites odeurs mais vous ne pourrez certainement pas être contaminé-e par le VIH. A moins d’avoir dans ces WC publics un rapport sexuel non protégé par un préservatif avec une personne elle-même contaminée…");
        addFact("Le SIDA est une maladie de PD et de toxicos", false, "A l'échelle mondiale, les femmes représentent aujourd'hui la moitié de toutes les infections par le VIH. De plus, la communauté homosexuelle, particulièrement concernée par l'épidémie, a été la première à se protéger et à faire de la prévention. Il n'y a pas de \"population à risque\", il n'y a que des \"pratiques à risques\".");
        addFact("Une personne qui a le SIDA ça se voit",false,"Il est impossible de dire qu’une personne est contaminée rien qu’en la regardant. Ce n’est pas parce qu’elle est maigre, qu’elle a des boutons ou qu’elle a un gros ventre qu’elle est porteuse du VIH. Des personnes qui paraissent en pleine forme peuvent être séropositives. Seul un test de dépistage spécifique permet de connaitre son statut sérologique.");
        addFact("Deux capotes ca vaux mieux qu'une",false,"Mettre deux préservatifs est inutile voire risqué. Les frottements des préservatifs entre eux peuvent en effet entrainer une déchirure et donc un risque de contamination. Évitez également les lubrifiants de fortune (margarine, beurre, etc.). Ils sont incompatibles avec les préservatifs en latex ou en polyuréthane. Utilisez plutôt un lubrifiant vendu en pharmacie ou en grande surface avec votre préservatif si ce dernier est insuffisamment lubrifié.");
        addFact("On ne peut pas avoir d'enfants quand on a le SIDA", false, "Le désir d’enfant est tout à fait envisageable quand on est séropositif-ve au VIH. Il est toutefois nécessaire d’anticiper la grossesse pour pouvoir bénéficier d’une prise en charge médicale adaptée et éviter le risque de contamination de l’enfant. En France métropolitaine, grâce aux traitements antirétroviraux, le taux de transmission mère-enfant du VIH-1 est passé à 0, 54 % sur la période 2005-2011 (contre 15-20 % en l’absence de traitement).");
        addFact("Le sida a disparu", false, "Moins présent dans les médias depuis plusieurs années, le sida est (malheureusement) toujours bel et bien présent. Si les traitements permettent aux personnes porteuses du VIH de \"vivre mieux\", ils ne guérissent pas. De la même façon, les avancées scientifiques ont également permis de faire reculer le taux de mortalité, mais 690.000 personnes sont décédées de maladies liées au sida dans le monde en 2019, d'après des données publiées par l'Organisation Mondiale de la Santé (OMS). Dans son dernier sondage réalisé par l'Ifop, Sidaction révèle également qu'environ 38 millions de personnes vivent avec le VIH dans le monde, et 1,7 million ont été infectées en 2020.");
        addFact("Le VIH et le sida, c'est pareil",false,"Il y a une différence entre l'infection par le VIH et le sida. Le virus de l'immunodéficience humaine (VIH) peut, sans traitement, être responsable du syndrome d'immunodéficience acquise (sida), phase la plus avancée de l'infection au VIH. Autrement dit, une personne qui a le sida est forcément infectée par le VIH alors que le contraire n'est pas vrai. Une personne infectée par le VIH n'a pas forcément développé le sida; d'où l'importance des traitements.");
        addFact("Une personne porteuse du VIH sous traitement peut transmettre le virus",false,"Si le préservatif demeure indispensable pour prévenir tout risque de transmission, une personne prenant \"un traitement antirétroviral tous les jours tel que prescrit et [atteignant] et [maintenant] une charge virale indétectable n'a aucun risque de transmettre le virus à un partenaire séronégatif pour le VIH\", rappelle Sida Info Service. Il s'agit du fameux \"I = I\", à savoir Indétectable = Intransmissible.");
        addFact("Le VIH peut se transmettre par un baiser", false, "Les méconnaissances sur les modes de transmission ont la vie dure malgré les nombreuses campagnes d'information sur le sujet. Le VIH ne se transmet ni par un baiser, ni par une piqûre de moustique, ni en utilisant les toilettes publiques, ni lorsque vous buvez dans le verre d'une personne séropositive. Pour faire plus simple, il ne s'agit pas d'une maladie contagieuse, donc pas de transmission par la salive, la toux, ou la transpiration. \"Le VIH se transmet le plus souvent lors de rapports sexuels non protégés s'il y a pénétration vaginale ou anale, (…) par un contact important avec du sang contaminé lors de partage de matériel d'injection ou en cas d'accident d'exposition (pour les soignants)\", rappelle Santé Publique France.");
        addFact("Le VIH est une condamnation à mort", false, "A la recherche d’une bonne nouvelle niveau santé mondiale ? La lutte contre le VIH/sida devrait être votre choix numéro 1.\n" +
            "Certes, le sida est la pandémie la plus meurtrière de l’histoire récente : elle a tué autant de gens que la Première guerre mondiale. Mais les progrès marqués contre la maladie depuis 30 ans sont phénoménaux. De nos jours, quiconque vivant avec le VIH mais qui suit un bon traitement sous antirétroviraux (ARV) a un risque quasi nul de tomber malade (le stade sida). Il ou elle peut couler de longs jours heureux et vivre des décennies en bonne santé.");
        addFact("Le préservatif est le seul moyen de ne pas infecter son partenaire ou de contracter le VIH",false,"Bien sûr, les préservatifs sont très efficaces pour éviter la contamination par le VIH, mais ce n’est pas la seule solution.\n" +
            "Plusieurs études ont montré que la prise optimale d’un traitement antirétroviral permet de réduire de 96% les risques de transmission du virus au sein de couples dont l’un des membres est séropositif. De nouveaux médicaments permettent même aux séronégatifs de se prémunir d’une infection.");
        addFact("Plus il y a de séropositifs dans un pays, plus il y a de décès liés au sida",false,"L’Afrique du Sud compte – et de loin – le plus grand nombre de personnes vivant avec le VIH dans le monde (6,8 millions). Chaque année, le sida y tue 140 000 personnes. Le chiffre est énorme ; mais il reste en-deçà du nombre de victimes du sida au Nigéria, un pays qui compte moitié moins de séropositifs. Pourquoi ? De nouveau, l’explication très simple : les Nigérians ont moins accès aux ARV que les Sud-Africains (22% de couverture antirétrovirale contre 45% en Afrique du Sud).");
        addFact("Moins il y a de séropositifs dans un pays, plus il est facile de lutter contre la maladie",false,"La logique voudrait que la République démocratique du Congo (RDC), où juste 1,2% de la population vit avec le VIH, soit davantage à même d’assurer un traitement ARV à ses citoyens qui en ont besoin que le Malawi qui compte proportionnellement près de dix fois plus de personnes séropositives. Après tout, les deux pays sont assez comparables, par exemple en termes de produit intérieur brut par habitant ou d’indice de développement humain. Et pourtant, le Malawi est parvenu à placer 50% de sa population séropositive sous ARV. En RDC, moins de 25% de ceux qui en ont besoin sont pris en charge.");
        addFact("Seuls les pays riches et stables peuvent assurer des traitements quotidiens à vie",false,"Cela pourrait sembler logique ; après tout, les systèmes de santé des pays riches ont déjà du mal à prendre en charge le nombre croissant de personnes souffrant de maladies chroniques : diabète, obésité, etc. Imaginez donc la situation dans un pays tel que le Malawi qui doit offrir des traitements quotidiens contre le VIH à 10% de sa population adulte, alors que le nombre de professionnels de la santé qui y travaille est six fois inférieur au minimum recommandé par l’Organisation mondiale de la santé (OMS).");

        //True facts
        addFact("Le SIDA est causé par un virus", true, "Le virus de l’immunodéficience humaine est un virus (de type rétrovirus) qui s’attaque aux cellules du système immunitaire, dont les lymphocytes T porteurs de la protéine CD4, et les détruit. Ainsi, comme tout virus, le VIH se sert des éléments présents dans la cellule pour se reproduire : il injecte son matériel génétique dans le lymphocyte qui fabrique alors et assemble les différents constituants viraux. Au terme de ce cycle, les virus nouvellement formés ressortent du lymphocyte.");
        addFact("La periode d'incubation est de 15 ans",true,"Aux premiers stades de l’infection, les malades ne présentent pas de symptômes. Le délai avant leur apparition est variable d’une personne à l’autre, de 5 à 15 ans, voire parfois plus.  Il existe en effet une période durant laquelle l’infection est « contenue » par le système immunitaire.");
        addFact("Le SIDA peux se transmetre de la mere a l enfant",true,"La voie maternelle : lors de l’accouchement ou de l’allaitement au sein, une mère atteinte du VIH peut contaminer son enfant. Le taux de transmission par ce biais a chuté drastiquement depuis l’apparition des traitements antirétroviraux.");
        addFact("Il existe un traitement contre le VIH",true,"Les médecins disposent aujourd’hui d’un arsenal thérapeutique conséquent pour lutter contre la maladie. Ces traitements ont permis une grande amélioration de la qualité et de l’espérance de vie des patients, au prix d’effets secondaires parfois importants. Malheureusement, le sida reste toujours une maladie incurable.");
        addFact("Un depistage precoce peu minimiser le risque d infection",true,"Le temps de latence entre l’infection et le développement du sida peut empêcher une prise en charge précoce de la pathologie. Ainsi, des tests de dépistage existent afin de détecter la présence du VIH dans le sang et donc authentifier l’infection.");
        addFact("La recherche sur le VIH continue", true, "Les recherches restent très actives sur tous les fronts pour combattre le virus. Du côté de la recherche fondamentale, un travail franco-international a isolé des cellules immunitaires particulières capables de contrôler l’infection chez certains patients. Ces lymphocytes T dits « cross réactifs » ont la capacité de détecter et de contrôler la propagation du virus. Leur caractérisation pourrait ouvrir une piste intéressante pour la construction d’un vaccin contre la maladie.");
        addFact("Les femmes ont des preservatifs",true,"Oui. Le Fémidon (préservatif féminin) est tout aussi efficace que le préservatif masculin. Il se positionne dans le vagin protégeant les deux partenaires lors d’une pénétration. À la différence du préservatif masculin en latex, il est composé de nitrile qui est une matière hypoallergénique et conductrice de chaleur (donc plus de plaisir !). Avantage non négligeable : Il peut être porté plusieurs heures et donc être mis en place bien avant la pénétration et retiré bien après l’éjaculation.");
        addFact("On peux se faire depister anonymement et gratuitement",true,"Dans un CDAG, Centre de Dépistage Anonyme et Gratuit. Il y en a au moins un par département. Un médecin vous reçoit et fait le point avec vous sur vos éventuelles prises de risque. C’est également lui qui vous remet les résultats du test. Ce test est gratuit et anonyme. Il faut compter une semaine entre le prélèvement sanguin et le retour des résultats.\n" +
            "Pour connaître les adresses des CDAG, consulter Sida Info Services (0800 840 800 ou www.sida-info-service.org).");
        addFact("Le VIH ne resiste que quelques secondes dehors",true,"En dehors du corps, lorsqu’il est à l’air libre, le VIH ne résiste que quelques secondes et meurt donc rapidement.");
        addFact("Dormir avec une personne seropositive est sans risques",true,"Oui, cela est tout à fait possible. Il n’y a absolument aucun risque de transmission du VIH quand on dort près d’une personne séropositive. Le VIH ne s’attrape pas via les gestes de la vie quotidienne d’une personne séropositive : manger ensemble, travailler dans le même espace, partager le même lieu de vie, se tenir la main, donner un bisou, etc…)");
        addFact("Un diagnostique tardif est une prise augmente les risques",true,"Un diagnostic tardif est un résultat positif à un test de dépistage VIH réalisé plusieurs années après la contamination. Le problème avec le diagnostic tardif est que la personne ignore sa séropositivité et peut donc infecter son·sa·ses partenaire·s en cas de prise de risque. De plus, cela retarde sa mise sous traitement, ce qui peut être dangereux pour sa santé.");
    }

    public ArrayList<Fact> getFacts() {
        return facts;
    }

    public Fact getARandomFact(){
        int i = new Random().nextInt(getFacts().size());
        return getFacts().get(i);
    }

    public static VIHFacts getInstance() {
        if(instance == null)
            new VIHFacts();
        return instance;
    }
}
